In [33]:
import numpy as np
import pandas as pd
import json

folder = 'webis_comparative_questions_2020_qi'
file = folder + '/english-questions.tsv'

# import webis_comparative_questions_2020_qi/english-questions.tsv
df = pd.read_csv(file, sep='\t')
df.head()

,difficulty,preference,context,aspect,direct,opinion,argument,reason,method,factoid,super,comp,question,dataset
0,0,0,0,0,0,0,0,0,0,0,0,0,do male seahorses give birth to the babies,g
1,0,0,0,0,0,0,0,0,0,0,0,0,who sings the vocals on feel it still,g
2,0,0,0,0,0,0,0,0,0,0,0,0,how did the guy from hogan's heroes die,g
3,0,0,0,0,0,0,0,0,0,0,0,0,which state was returned to spain after the re...,g
4,0,0,0,0,0,0,0,0,0,0,0,0,do you need a background check to buy a shotgu...,g

In [34]:
# keep 2 columns, comp and question
df = df[['comp', 'question']]
# rename to label and text
df.columns = ['label', 'text']
df.head()

   label                                               text
0      0         do male seahorses give birth to the babies
1      0              who sings the vocals on feel it still
2      0            how did the guy from hogan's heroes die
3      0  which state was returned to spain after the re...
4      0  do you need a background check to buy a shotgu...

In [35]:
# split df into train and test
np.random.seed(42)
msk = np.random.rand(len(df)) < 0.8
train = df[msk]
test = df[~msk]

train.to_csv(folder + '/train.csv', sep='\t', index=False)
test.to_csv(folder + '/test.csv', sep='\t', index=False)